#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d7o9p6d7vvec739kvfig-a.oregon-postgres.render.com/moneymanager_xmv7
spring.datasource.username=moneymanager_xmv7_user
spring.datasource.password=bQYKKkHyMPuuUYQH8p2u8RGjRlgJZwtk